### ISSUE TITLE
Assembler: Need a way to get pointer to code location.

### ISSUE THREAD

**Issue by Sonicadvance1** [lioncash/biscuit#5]
Brought about with https://github.com/FEX-Emu/FEX/pull/1640, Need a way in the assembler to either get the pointer to the current  Assembler's cursor position for branching to, or a way to get a label's bound position.
Either way, need the pointer.

**Comment by lioncash** [comment]
Pushed a few buffer access functions in this commit: https://github.com/lioncash/biscuit/commit/a7e520f9d288cf1a0ef2fc8fc23f27b512b2a9b5

**Comment by Sonicadvance1** [comment]
That works! Thanks!
