### ISSUE TITLE
Allocate executable memory for the code buffer

### ISSUE THREAD

**Issue by pazamelin** [lioncash/biscuit#9]
Hello!

There seems to be no way of executing the generated code if memory is managed and allocated by [CodeBuffer](https://github.com/lioncash/biscuit/blob/daa96a12f7100c97d7fb55ae8ec7d8a7250db925/include/biscuit/code_buffer.hpp#L18).
The CodeBuffer class always allocates memory w/o execute permissions.

Is this an expected behavior? Are you planning to change it in the future?  Would you accept external contributions?

Thanks,

**Comment by lioncash** [comment]
I've added an option to make the code buffer use mmap, which allows setting exec/write permissions interchangeably on the buffer, which should satisfy what you need (and also handle W^X at the same time) in https://github.com/lioncash/biscuit/commit/c39e55e929a78dc8ff1854a9ff88e1c3e36f6d55. Let me know if that works for you

**Comment by pazamelin** [comment]
It works perfectly for me, thank you!

I compile with `-D BISCUIT_CODE_BUFFER_MMAP=ON` and call `CodeBuffer::SetExecutable()` after code generation.

**Comment by lioncash** [comment]
Great! Glad to hear it works out. 

If you have any other issues you stumble upon, feel free to let me know and I'll see what I can do about it
